In [14]:
import pandas as pd
df = pd.read_csv(r"/home/ahmadjon/Desktop/practise/Data/Students_Performance.csv")

# Dublicate qatorlar soni

In [15]:
dublciate_count = df.duplicated().sum()
print(dublciate_count)

0

# Duplicate qatorlarni chiqarish

In [16]:
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

# Barcha duplicate qatorlarni (birinchi nusxasi bilan birga) ko'rish

In [17]:
duplicates = df[df.duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

### 8126 va 8127 bir xil qiymatga ega

### Duplicate foizizni ko'rsatish

In [18]:
duplicate_percent = (df.duplicated().sum() / len(df)) * 100
print(f"Duplicate percentage: {duplicate_percent: .2f}")

Duplicate percentage:  0.00

# Duplicate mavjud yo'qligini tekshirish

In [19]:
if df.duplicated().any():
    print("Datasetda duplicate mavjud")
else:
    print("Datasetda duplicate yo'q")

Datasetda duplicate yo'q

Tekshirish

In [20]:
df[df.duplicated(subset=["race/ethnicity", "parental level of education"])]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
12,female,group B,high school,standard,none,65,81,73
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
print(df.shape)
df  = df.drop_duplicates()
print(df.shape)

(1000, 8)
(1000, 8)

In [22]:
print("=" * 50)
print("Duplicated Analysis")
print("=" * 50)

print(f"Dataset Shape : {df.shape}")
print(f"Dataset Shape : {df.duplicated().sum()}")
print(f"Dataset Shape : {df.duplicated().sum()/len(df)*100:.2f}%")

if df.duplicated().any():
    print("\nRemoving duplicates")
    df =df.drop_duplicates()
    print(f"New Shape : {df.shape}")
else:
    print("\nNo duplicates found.")

==================================================
Duplicated Analysis
==================================================
Dataset Shape : (1000, 8)
Dataset Shape : 0
Dataset Shape : 0.00%

No duplicates found.

# Faqat unknown mavjud ustunlarni chiqarish

In [23]:
unknown_counts = (df == "unknown").sum()
unknown_counts = unknown_counts[unknown_counts > 0]
print(unknown_counts)

Series([], dtype: int64)

# Datasetda barcha unknown qatrolarni ko'rish

In [24]:
unknown_counts = df[df.eq("unknown").any(axis=1)]
unknown_counts

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

# Unknown qiymatlarni NaN ga almashtirish (eng tavsiya etiladi)

In [25]:
import numpy as np
df.replace("unknown", np.nan, inplace=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Unknown qiymatlarni Mode bilan to'ldirish

In [26]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].replace("unknown", df[col].mode()[0])

/tmp/ipykernel_39232/2027925542.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [27]:
print("=" * 50)
print("unknown counts")
print("=" * 50)

# unknown soni
unknown_counts = (df == "unkown").sum()
unknown_counts = unknown_counts[unknown_counts > 0]


print(unknown_counts)

# unknown foizi
print("\nPercentage: ")
print((unknown_counts / len(df) * 100).round(2))

# unknown -> NaN
df.replace("unknown", np.nan, inplace=True)

print("\nAfter replacement")
print(df.isnull().sum())

==================================================
unknown counts
==================================================
Series([], dtype: int64)

Percentage:
Series([], dtype: float64)

After replacement
gender                          0
race/ethnicity                 11
parental level of education    21
lunch                          12
test preparation course         4
math score                      0
reading score                   0
writing score                   0
dtype: int64